// Thai UI for this teaching tool; deck content remains teacher-authored.
export const thai = {
  'Fullscreen is unavailable. Continue in this window.': 'ไม่สามารถเปิดเต็มหน้าจอได้ ใช้งานต่อในหน้าต่างนี้ได้',
  'Lesson mode': 'โหมดสอน', '← Back to preparation': '← กลับไปเตรียมบทเรียน',
  'Review': 'ทบทวน', 'Fullscreen': 'เต็มหน้าจอ', 'Exit fullscreen': 'ออกจากเต็มหน้าจอ',
  'Deck complete': 'จบชุดบัตรแล้ว', 'Well done!': 'เก่งมาก!',
  'Marked for review: ': 'บัตรที่เลือกไว้ทบทวน: ', 'Review marked cards': 'ทบทวนบัตรที่เลือก',
  'Finish lesson': 'จบบทเรียน', 'Question': 'โจทย์', 'Answer': 'คำตอบ', 'Explanation': 'คำอธิบาย',
  'Previous': 'ก่อนหน้า', 'Show answer': 'แสดงคำตอบ', 'Hide answer': 'ซ่อนคำตอบ',
  'Show explanation': 'แสดงคำอธิบาย', 'Review later': 'ทบทวนภายหลัง', 'Finish': 'จบ', 'Next →': 'ถัดไป →',
  'Space: answer → explanation → next · ← →: navigate · R: mark · Esc: exit': 'Space: คำตอบ → คำอธิบาย → ถัดไป · ← →: เปลี่ยนบัตร · R: เลือกทบทวน · Esc: ออก',
  'Discard unsaved fields?': 'ละทิ้งข้อมูลที่ยังไม่ได้บันทึกหรือไม่?',
  'Maximum 100 decks.': 'สร้างได้สูงสุด 100 ชุด',
  'Enter a question and an answer.': 'กรุณากรอกโจทย์และคำตอบ',
  'Maximum 500 cards per deck.': 'แต่ละชุดมีได้สูงสุด 500 บัตร',
  'Card saved.': 'บันทึกบัตรแล้ว',
  'Import failed. Use a Math Flashcards export (up to 5 MB, 100 decks in total).': 'นำเข้าไม่สำเร็จ กรุณาใช้ไฟล์ที่ส่งออกจาก Math Flashcards (ไม่เกิน 5 MB และรวมไม่เกิน 100 ชุด)',
  'Flashcards for maths lessons and tutoring.': 'บัตรคำสำหรับสอนคณิตศาสตร์ในห้องเรียนและสอนพิเศษ',
  'Projects': 'ผลงาน', 'Language': 'ภาษา', 'Theme': 'ธีม', 'Teaching tool': 'เครื่องมือสำหรับครู',
  'Prepare your questions. Open them on screen. Teach at your own pace.': 'เตรียมโจทย์ แสดงบนหน้าจอ แล้วสอนตามจังหวะของคุณ',
  'Export all decks': 'ส่งออกทุกชุด', 'Import JSON': 'นำเข้า JSON',
  'Decks live only in this browser. Export a copy for school or backup.': 'ชุดบัตรจะเก็บไว้ในเบราว์เซอร์นี้เท่านั้น ส่งออกไฟล์เพื่อนำไปใช้ที่โรงเรียนหรือสำรองข้อมูล',
  'Saved data could not be read and has not been changed. New changes will replace it — back up browser data first.': 'ไม่สามารถอ่านข้อมูลที่บันทึกไว้ได้ และยังไม่ได้แก้ไขข้อมูลเดิม การบันทึกใหม่จะแทนที่ข้อมูลเดิม กรุณาสำรองข้อมูลเบราว์เซอร์ก่อน',
  'Changes are only in memory. Export your decks before closing this page.': 'การเปลี่ยนแปลงยังไม่ได้บันทึกถาวร กรุณาส่งออกชุดบัตรก่อนปิดหน้านี้',
  'Import preview': 'ตรวจสอบก่อนนำเข้า',
  'New copies will be added. Existing decks will stay unchanged.': 'ระบบจะเพิ่มสำเนาชุดบัตรใหม่ โดยไม่แก้ไขชุดที่มีอยู่',
  'Decks imported.': 'นำเข้าชุดบัตรแล้ว', 'Add decks': 'เพิ่มชุดบัตร', 'Cancel': 'ยกเลิก',
  'My decks': 'ชุดบัตรของฉัน',
  'The starter decks are examples. Adapt them for your class.': 'ชุดเริ่มต้นเป็นตัวอย่าง สามารถปรับให้เหมาะกับชั้นเรียนของคุณได้',
  'cards': 'บัตร', 'New deck name': 'ชื่อชุดบัตรใหม่', 'Create deck': 'สร้างชุดบัตร', 'Delete deck': 'ลบชุดบัตร',
  'Rename deck': 'ชื่อชุดบัตรใหม่', 'Rename': 'เปลี่ยนชื่อ', 'Shuffle before starting': 'สลับลำดับก่อนเริ่ม',
  'Unsaved fields will not be in the lesson. Continue?': 'ข้อมูลที่ยังไม่ได้บันทึกจะไม่รวมในบทเรียน ดำเนินการต่อหรือไม่?',
  'Start lesson →': 'เริ่มสอน →', 'Edit card': 'แก้ไขบัตร', 'New card': 'บัตรใหม่',
  'Explanation (optional)': 'คำอธิบาย (ไม่บังคับ)',
  'Plain text: 1/2, ×, ÷, x². Advanced formula formatting is not supported yet.': 'ใช้ข้อความธรรมดา เช่น 1/2, ×, ÷, x² ยังไม่รองรับการจัดรูปแบบสูตรขั้นสูง',
  'Save card': 'บันทึกบัตร', 'Cancel edit': 'ยกเลิกการแก้ไข', 'Paste from spreadsheet': 'วางจากตาราง',
  'No header: question, answer, optional explanation. Tab-separated columns, one card per row. Use the form above for multiline cells.': 'ไม่ต้องใส่หัวตาราง: โจทย์ คำตอบ และคำอธิบาย (ไม่บังคับ) คั่นคอลัมน์ด้วยแท็บ หนึ่งบัตรต่อหนึ่งแถว หากมีหลายบรรทัดในเซลล์ ให้ใช้แบบฟอร์มด้านบน',
  'Spreadsheet rows': 'ข้อมูลจากตาราง', 'Preview': 'ดูตัวอย่าง', 'Ready cards: ': 'บัตรที่พร้อมเพิ่ม: ',
  'Fix rows: ': 'กรุณาแก้ไขแถว: ', 'First 20 rows shown.': 'แสดง 20 แถวแรก',
  'Cards added.': 'เพิ่มบัตรแล้ว', 'Add cards': 'เพิ่มบัตร', 'Up to 500 cards per deck.': 'สูงสุด 500 บัตรต่อชุด',
  'Deck cards': 'บัตรในชุด',
  'Add your first card using the form or spreadsheet paste.': 'เพิ่มบัตรแรกด้วยแบบฟอร์มหรือวางข้อมูลจากตาราง',
  'Edit': 'แก้ไข', 'Delete this card?': 'ลบบัตรนี้หรือไม่?', 'Delete': 'ลบ',
  'Create your first deck': 'สร้างชุดบัตรแรกของคุณ',
  'Or import a previously exported JSON file.': 'หรือนำเข้าไฟล์ JSON ที่เคยส่งออกไว้',
};
